### ISSUE TITLE
Empty title in layout

### ISSUE THREAD

**Issue by arongergely** [rodekruis/sims_maps_qgis_plugin#10]
Newly generated layouts have empty title boxes (RC_title). 
Maybe add a "Title" field in the Create Layout window?
Also, empty text boxes could default to a dummy string (item name or Lorem Impsum, etc) so new users can still see they are there.

**Comment by raymondnijssen** [comment]
Not sure if this is a good plan. But you can add default strings for layout items in the layout config file: 
https://github.com/rodekruis/sims_maps_qgis_plugin/blob/7fc2cba097551de6fc01da5e59582ca8350488ab/sims_maps/layout_config.py#L2

**Comment by raymondnijssen** [comment]
This PR sets the layout title to the layout name, not leaving it empty: https://github.com/rodekruis/sims_maps_qgis_plugin/pull/24

**Comment by raymondnijssen** [comment]
I'm not in favour of setting dummy values to the other text boxes, because they would appear in the exported maps. And if you don't want them, you would need to manually empty them

**Comment by arongergely** [comment]
Thanks, #24 fixes the issue.  You are right about the dummy texts being a bad idea, it can pollute the map layouts when a user would forget to edit them.
