### ISSUE TITLE
Automate generation of specific maps that are often generated / updated

### ISSUE THREAD

**Issue by ffisc** [rodekruis/sims_maps_qgis_plugin#18]
Some maps are regularly updated as the situation changes. Right now this is done manually, but there is potential for automation. Perhaps a particularly problematic map type is the Regional Movement Coordination Map, where there is a lot of manual work still involved.

A very useful addition would be if the user could perhaps provide a tabular input of `(Partner, Intervention type, Location)`, and the plugin would then generate the map based on this information.

Obs. This is an enhancemment but I haven't been able to add the relevant tag

**Comment by raymondnijssen** [comment]
In my opinion this kind of functionality should be implemented in another plugin with a more data collecting/generating/visualisation purpose. This plugin should focus on creating layouts.

Nevertheless, this is a great idea so I let's leave it alive here until a new plugin has born!

**Comment by arongergely** [comment]
Hi @ffisc, thanks for submitting your idea. I also agree with @raymondnijssen 's thoughts - this sort of high level automation is not the scope of the plugin and should be done outside of it.
